docker-build-master:
  stage: build
  image: docker:latest
  before_script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - main

deploy-service-master:
  stage: deploy
  script:
    - apk add --update curl
    - curl -XPOST http://host.docker.internal:9000/api/webhooks/49e55708-fadc-4f81-b9ba-f778914d3915
  only:
    - main
